# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termen', models.CharField(max_length=200)),
                ('parinte', models.CharField(max_length=200)),
                ('relatie', models.CharField(max_length=100)),
            ],
        ),
    ]
